seml:
  executable: main_seml.py
  name: synthetic_d3pm
  output_dir: experiments/synthetic_d3pm
  project_root_dir: ../..
  conda_environment: /ceph/hdd/students/schmitj/miniconda3/base

slurm:
  experiments_per_job: 1
  sbatch_options:
    # partition: gpu_large
    gres: gpu:1       # num GPUs
    mem: 16G          # memory
    cpus-per-task: 1  # num cores
    time: 0-23:00     # max time, D-HH:MM

fixed:
  data:
    dataset: synthetic_graph
    train_data_path: '/ceph/hdd/students/schmitj/MA_Diffusion_based_trajectory_prediction/data/synthetic.h5'
    test_data_path: '/ceph/hdd/students/schmitj/MA_Diffusion_based_trajectory_prediction/data/synthetic_test.h5'
    history_len: 5
    future_len: 2
    num_classes: 1
    edge_features: ['one_hot_edges']
    # edge_features: ['one_hot_edges', 'edge_orientations']

  diffusion_config:
    type: linear
    start: 1.e-4  # 1e-4 gauss, 0.02 uniform
    stop: 0.02  # 0.02 gauss, 1. uniform
    num_timesteps: 1000
  
  model:
    name: edge_encoder
    hidden_channels: 256
    time_embedding_dim: 128
    condition_dim: 256
    out_ch: 1
    num_heads: 1
    dropout: 0.1
    model_output: logits
    model_prediction: x_start  # Options: 'x_start','xprev'
    transition_mat_type: gaussian  # Options: 'gaussian','uniform','absorbing'
    transition_bands: null
    loss_type: cross_entropy_x_start  # Options: kl, cross_entropy_x_start, hybrid
    hybrid_coeff: 0.001  # Only used for hybrid loss type.
  
  training:
    batch_size: 1
    optimizer: adam
    lr: 0.0001
    gradient_accumulation: True
    gradient_accumulation_steps: 16
    num_epochs: 30000
    # learning_rate_warmup_steps: 0
    lr_decay: 0.000005 # = 0.1/num_epochs so that lr at the end is 1/10 of lr at beginning
    log_loss_every_steps: 20

  testing:
    batch_size: 1
  
  wandb:
    exp_name: "synthetic_d3pm_seml_lr_decay"
    project: "trajectory_prediction_using_denoising_diffusion_models"
    entity: "joeschmit99"
    job_type: "train"
    notes: "New lr decay"
    tags: ["synthetic_graph", "edge_encoder"]

  eval: False

random:
  samples: 1
  seed: 7059