seml:
  executable: main_seml.py
  name: tdrive_d3pm_residual
  output_dir: experiments/tdrive_d3pm_residual
  project_root_dir: ../..
  conda_environment: /ceph/hdd/students/schmitj/miniconda3/envs/d3pm

slurm:
  experiments_per_job: 1
  sbatch_options:
    partition: gpu_gtx1080
    gres: gpu:1     # num GPUs
    mem: 64G          # memory
    cpus-per-task: 8  # num cores
    time: 1-23:00     # max time, D-HH:MM

fixed:
  data:
    dataset: tdrive
    train_data_path: '/ceph/hdd/students/schmitj/MA_Diffusion_based_trajectory_prediction/data/tdrive_train.h5'
    val_data_path: '/ceph/hdd/students/schmitj/MA_Diffusion_based_trajectory_prediction/data/tdrive_val.h5'
    num_classes: 2
    pos_encoding_dim: 16
    edge_features: ['one_hot_edges', 'coordinates', 'pos_encoding']

  diffusion_config:
    start: 0.00001  # 1e-4 gauss, 0.02 uniform
    stop: 0.005  # 0.02 gauss, 1. uniform
    num_timesteps: 50
  
  model:
    dropout: 0.1
    model_output: logits
    theta: 1.0 # controls strength of conv layers in residual model
    model_prediction: x_start  # Options: 'x_start','xprev'
    transition_bands: null
    loss_type: cross_entropy_x_start  # Options: kl, cross_entropy_x_start, hybrid
    hybrid_coeff: 0.001  # Only used for hybrid loss type.
    num_heads: 2
    num_layers: 2
    condition_dim: 32
    hidden_channels: 64
    time_embedding_dim: 16
  
  training:
    lr: 0.005
    device: cuda
    batch_size: 8
    optimizer: adam
    gradient_accumulation: False
    gradient_accumulation_steps: 64
    learning_rate_warmup_steps: 300 # previously 10000
    num_epochs: 500
    lr_decay: 0.9999 # previously 0.9999
    log_loss_every_steps: 1
    log_metrics_every_steps: 2
    save_model: True
    save_model_every_steps: 2

  testing:
    batch_size: 1
    model_path: '/ceph/hdd/students/schmitj/MA_Diffusion_based_trajectory_prediction/experiments/synthetic_d3pm_without_last_two_relu_longer_training/synthetic_d3pm_without_last_two_relu_longer_training.pth'
    number_samples: 1
    eval_every_steps: 10
    
  wandb:
    exp_name: "tdrive_residual"
    project: "trajectory_prediction_using_denoising_diffusion_models"
    entity: "joeschmit99"
    job_type: "train"
    notes: ""
    tags: ["tdrive", "edge_encoder_residual"]

  eval: False

grid:
  data.history_len:
    type: choice
    options:
      - 5
      - 10
  data.future_len:
    type: choice
    options:
      - 2
      - 5
      - 10
      - 20
  diffusion_config.type:
    type: choice
    options:
      - 'linear'
      - 'cosine'
  model.transition_mat_type:
    type: choice
    options:
      - 'custom'
      # - 'marginal_prior'
  model.name:
    type: choice
    options:
      # - edge_encoder_mlp
      # - edge_encoder
      - edge_encoder_residual

random:
  samples: 1
  seed: 7059