seml:
  executable: main_seml.py
  name: pneuma_d3pm_residual
  output_dir: experiments/pneuma_d3pm_residual
  project_root_dir: ../..
  conda_environment: /ceph/hdd/students/schmitj/miniconda3/envs/d3pm

slurm:
  experiments_per_job: 1
  sbatch_options:
    partition: gpu_gtx1080
    gres: gpu:1     # num GPUs
    mem: 64G          # memory
    cpus-per-task: 8  # num cores
    time: 1-03:00     # max time, D-HH:MM

fixed:
  data:
    dataset: pneuma
    train_data_path: '/ceph/hdd/students/schmitj/MA_Diffusion_based_trajectory_prediction/data/pneuma_train.h5'
    val_data_path: '/ceph/hdd/students/schmitj/MA_Diffusion_based_trajectory_prediction/data/pneuma_val.h5'
    history_len: 5
    num_classes: 2

  diffusion_config:
    start: 1e-5  # 1e-5 custom, 0.01 prior
    stop: 0.09  # 0.09 custom, 0.5 prior
    num_timesteps: 100
  
  model:
    name: edge_encoder_residual
    dropout: 0.1
    hidden_channels: 64
    time_embedding_dim: 16
    num_heads: 3
    num_layers: 3
    pos_encoding_dim: 16
    model_output: logits
    theta: 1.0 # controls strength of conv layers in residual model
    model_prediction: x_start  # Options: 'x_start','xprev'
    transition_bands: null
    loss_type: cross_entropy_x_start  # Options: kl, cross_entropy_x_start, hybrid
    hybrid_coeff: 0.001  # Only used for hybrid loss type.
  
  training:
    lr: 0.009
    device: cuda
    batch_size: 64
    optimizer: adam
    gradient_accumulation: False
    gradient_accumulation_steps: 1
    learning_rate_warmup_steps: 40 
    num_epochs: 60
    lr_decay: 0.99 # previously 0.9999
    log_loss_every_steps: 1
    log_metrics_every_steps: 2
    save_model: True
    save_model_every_steps: 2
    pretrained: False

  testing:
    batch_size: 64
    model_path: '/ceph/hdd/students/schmitj/MA_Diffusion_based_trajectory_prediction/experiments/synthetic_d3pm_without_last_two_relu_longer_training/synthetic_d3pm_without_last_two_relu_longer_training.pth'
    number_samples: 10
    eval_every_steps: 10
    
  wandb:
    exp_name: "pneuma_residual"
    project: "trajectory_prediction_using_denoising_diffusion_models"
    entity: "joeschmit99"
    job_type: "train"
    notes: ""
    tags: ["pneuma", "edge_encoder_residual"]

  eval: False

grid:
  data.future_len:
    type: choice
    options:
      - 2
      - 5
      - 10
  data.edge_features:
    type: choice
    options:
      #- ['one_hot_edges', 'coordinates']
      - ['one_hot_edges', 'coordinates', 'pos_encoding']
      - ['one_hot_edges', 'coordinates', 'pos_encoding', 'pw_distance']
      #- ['one_hot_edges', 'coordinates', 'pos_encoding', 'edge_angles']
      #- ['one_hot_edges', 'coordinates', 'pos_encoding', 'pw_distance', 'edge_length']
      - ['one_hot_edges', 'coordinates', 'pos_encoding', 'pw_distance', 'edge_length', 'edge_angles']
      - ['one_hot_edges', 'coordinates', 'pos_encoding', 'pw_distance', 'edge_length', 'edge_angles', 'num_pred_edges']
      #- ['one_hot_edges', 'pw_distance', 'edge_length', 'edge_angles']
      #- ['coordinates', 'pos_encoding', 'pw_distance', 'edge_length', 'edge_angles']
      - ['coordinates', 'pw_distance', 'edge_length', 'edge_angles']
      
  diffusion_config.type:
    type: choice
    options:
      # - 'linear'
      - 'cosine'
  model.transition_mat_type:
    type: choice
    options:
      - 'custom'
      - 'marginal_prior'

random:
  samples: 1
  seed: 7059